#! /bin/bash
### BEGIN INIT INFO
# Provides:          yarprun
# Required-Start:    yarpserver hostname $local_fs $network$ $named $remote_fs $syslog $time
# Required-Stop:     yarpserver hostname $local_fs $network$ $named $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: yarprun - YARP run daemon
# Description:       YARP run daemon
### END INIT INFO

DAEMON=/usr/bin/yarprun
NAME=yarprun
PIDFILE=/var/run/yarp/$NAME.pid
DESC="yarprun daemon"
PORT=/$HOSTNAME
YARPRUN_OPTIONS="--server $PORT"

if [ -f /etc/default/yarprun ]; then
        . /etc/default/yarprun
fi

unset TMPDIR

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

SSD_OPTIONS="--quiet --pidfile $PIDFILE --make-pidfile"

export YARP_CONFIG_HOME=/etc/yarp

case "$1" in
  start)
    log_begin_msg "Starting $DESC: $NAME ($DAEMON)"

    mkdir -p `dirname "$PIDFILE"`
    start-stop-daemon --start --oknodo --background $SSD_OPTIONS --exec $DAEMON -- $YARPRUN_OPTIONS
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping $DESC: $NAME ($DAEMON)"
    start-stop-daemon --stop --retry 5 --oknodo $SSD_OPTIONS --name $NAME
    log_end_msg $?
    rm -f $PIDFILE
    ;;
  restart|force-reload)
    log_begin_msg "Restarting $DESC: $NAME ($DAEMON)"
    if start-stop-daemon --stop --retry 5 --oknodo $SSD_OPTIONS --name $NAME; then
      start-stop-daemon --start --background $SSD_OPTIONS --exec $DAEMON -- $YARPRUN_OPTIONS
    fi
    log_end_msg $?
    ;;
  status)
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
  *)
    N=/etc/init.d/${0##*/}
    echo "Usage: $N {start|stop|force-reload|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
