# external
set(GazeboYARPPlugins_TAG master)
set(iDynTree_TAG f0346c1)
set(kdl_codyco_TAG 12bbb14)
set(kdl_format_io_TAG 6890e69)
set(paramHelp_TAG de9f652)
set(pykdl_utils_TAG a8683c8)
set(roboptim-core_TAG v3.1)
set(roboptim-core-plugin-ipopt_TAG v3.1)
set(roboptim-capsule_TAG v3.1)
set(TinyXML_TAG 8459459)
set(YARP_TAG a2b38a0)
set(YCM_TAG b327e75)

set(centralized_inverse_kinematics_TAG master)
set(drc_shared_TAG master)
set(idynutils_TAG master)
set(OpenSoT_TAG devel)
set(robot_state_publisher_ext_TAG master)
set(simple_homing_TAG master)
set(walking_TAG master)
set(yarp_ros_joint_state_publisher_TAG master)

# COMAN
set(comanapp_TAG VVV15)
set(comaninterface_TAG VVV15)
set(comanmod_TAG VVV15)
set(COMAN_shared_TAG emergency)
