# external
set(GazeboYARPPlugins_TAG master)
set(iDynTree_TAG f0346c1)
set(paramHelp_TAG de9f652)
set(roboptim-core_TAG v3.1)
set(roboptim-core-plugin-ipopt_TAG v3.1)
set(roboptim-capsule_TAG v3.1)
set(TinyXML_TAG 8459459)
set(YARP_TAG 2fae615)
set(YCM_TAG b327e75)

set(centralized_inverse_kinematics_TAG master)
set(drc_shared_TAG master)
set(idynutils_TAG master)
set(OpenSoT_TAG master)
set(robot_state_publisher_ext_TAG master)
set(simple_homing_TAG master)
set(walking_TAG master)
set(yarp_ros_joint_state_publisher_TAG master)

# COMAN
set(comanapp_TAG VVV15)
set(comaninterface_TAG VVV15)
set(comanmod_TAG VVV15)
set(COMAN_shared_TAG emergency)
